trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
    displayName: 'Configurar Java 17'

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'test'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
    displayName: 'Ejecutar pruebas automatizadas con Maven'