server.tomcat.additional-tld-skip-patterns=htmlunit-*.jar,jetty-*.jar

# Base de datos en memoria
spring.datasource.url=jdbc:hsqldb:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create

# OpenXava login
spring.security.user.name=admin
spring.security.user.password=admin

# Puerto
server.port=8080
naviox.defaultUserName=admin
naviox.defaultPassword=admin
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration