CREATE TABLE IF NOT EXISTS OXUSER (ID VARCHAR(32) NOT NULL, NAME VARCHAR(50), PASSWORD VARCHAR(50), EMAIL VARCHAR(100), PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS OXROLE (ID VARCHAR(32) NOT NULL, NAME VARCHAR(50), PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS OXUSER_OXROLE (OXUSER_ID VARCHAR(32), OXROLES_ID VARCHAR(32));

INSERT INTO OXUSER (ID, NAME, PASSWORD) VALUES ('admin', 'Administrador', 'admin');
INSERT INTO OXROLE (ID, NAME) VALUES ('admin', 'admin');
INSERT INTO OXUSER_OXROLE (OXUSER_ID, OXROLES_ID) VALUES ('admin', 'admin');